exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

title: Ruby on Rails
description: A web-application framework that includes everything needed to create database-backed web applications according to the Model-View-Controller (MVC) pattern.
twitter:
  username: rails
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/4223
